spring:
  application:
    name: WeatherApiConsuming
    ApiKey: ${API_KEY}
    cors:
      allowed-origins: "https://weather-frontend-qxwf.onrender.com"
  cache:
    type: redis
    redis:
      time-to-live: 10h
  data:
    redis:
      client-name: cache
      url: ${REDIS_URL}

server:
  port: ${PORT:8080}
  ssl:
    enabled: false
