server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  application:
    name: WeatherApiConsuming

weather:
  apiKey: ${API_KEY}

cors:
  allowed-origins: "https://weather-frontend-qxwf.onrender.com"
