spring:
  application:
    name: WeatherApiConsuming
    ApiKey: ${API_KEY}
    cors:
      allowed-origins: "https://weather-frontend-qxwf.onrender.com"
  main:
    lazy-initialization: true
    banner-mode: off
  profiles:
    active: prod

